companySymbols = {
    "Apple": "AAPL",
    "Microsoft": "MSFT",
    "Amazon": "AMZN",
    "Alphabet": "GOOGL",
    "Facebook": "FB",
    "Tesla": "TSLA",
    "Johnson & Johnson": "JNJ",
    "JPMorgan Chase": "JPM",
    "Walmart": "WMT",
    "Procter & Gamble": "PG",
    "Bank of America": "BAC",
    "Netflix": "NFLX",
    "Visa": "V",
    "Mastercard": "MA",
    "Intel": "INTC",
    "Cisco": "CSCO",
    "Boeing": "BA",
    "General Electric": "GE",
    "Exxon Mobil": "XOM",
    "Chevron": "CVX",
    "IBM": "IBM",
    "Coca-Cola": "KO",
    "PepsiCo": "PEP",
    "McDonald's": "MCD",
    "Disney": "DIS",
    "AT&T": "T",
    "Verizon": "VZ",
    "NVIDIA": "NVDA",
    "AMD": "AMD",
    "Salesforce": "CRM",
    "Adobe": "ADBE",
    "Oracle": "ORCL",
    "Home Depot": "HD",
    "Lowe's": "LOW",
    "IBM": "IBM",
    "Intel": "INTC",
    "General Motors": "GM",
    "Ford Motor Company": "F",
    "Twitter": "TWTR",
    "Snap Inc.": "SNAP",
    "Uber Technologies": "UBER",
    "Lyft": "LYFT",
    "Alibaba Group": "BABA",
    "Tencent Holdings": "TCEHY",
    "Berkshire Hathaway": "BRK.A",
    "Sony": "SONY",
    "Nintendo": "NTDOY",
    "Mitsubishi": "MSBHY",
    "Hyundai Motor": "HYMTF",
    "Samsung Electronics": "SSNLF",
    "Sony Corporation": "SNE",
    "Toyota Motor": "TM",
    "Honda Motor": "HMC",
    "Nestle": "NSRGY",
    "Unilever": "UL",
    "Nike": "NKE",
    "Adidas": "ADDYY",
    "LVMH Moet Hennessy Louis Vuitton SE": "LVMUY",
    "Ferrari": "RACE",
    "Pfizer": "PFE",
    "Merck & Co.": "MRK",
    "Bristol-Myers Squibb": "BMY",
    "GlaxoSmithKline": "GSK",
    "Novartis AG": "NVS",
    "Roche Holding AG": "ROG",
    "Sanofi": "SNY",
    "AstraZeneca": "AZN",
    "AbbVie Inc.": "ABBV",
    "Gilead Sciences": "GILD",
    "Biogen Inc.": "BIIB",
    "Vertex Pharmaceuticals": "VRTX",
    "Regeneron Pharmaceuticals": "REGN",
    "Eli Lilly and Company": "LLY",
    "Bayer AG": "BAYRY",
    "Siemens AG": "SIEGY",
    "BMW AG": "BMWYY",
    "Daimler AG": "DDAIF",
    "Volkswagen AG": "VWAGY",
    "Audi AG": "AUDVF",
    "Porsche SE": "POAHY",
    "BASF SE": "BASFY",
    "Lufthansa Group": "DLAKY",
    "Deutsche Post AG": "DPSGY",
    "Deutsche Bank AG": "DB",
    "Allianz SE": "ALIZF",
    "Munich Re": "MURGY",
    "Bayerische Motoren Werke AG": "BMWYY",
    "Thyssenkrupp AG": "TYEKF",
    "Volkswagen Group": "VWAGY",
    "Continental AG": "CTTAY",
    "Airbus SE": "EADSY",
    "Banco Santander": "SAN",
    "BBVA": "BBVA",
    "Iberdrola": "IBDRY",
    "Telefonica": "TEF",
    "Inditex": "IDEXY",
    "Repsol": "REPYY",
    "Eni SpA": "E",
    "TotalEnergies": "TTE",
    "Royal Dutch Shell": "RDS.A",
    "BP plc": "BP",
    "Nokia Corporation": "NOK",
    "Ericsson": "ERIC",
    "Accenture": "ACN",
    "Capgemini": "CAP",
    "Infosys": "INFY",
    "Tata Consultancy Services": "TCS",
    "Wipro": "WIT",
    "Cognizant": "CTSH",
    "Hewlett Packard Enterprise": "HPE",
    "Dell Technologies": "DELL",
    "Lenovo Group": "LNVGY",
    "Sony Corporation": "SNE",
    "Panasonic Corporation": "PCRFY",
    "Hitachi Ltd.": "HTHIY",
    "Mitsubishi Electric Corporation": "MIELY",
    "Fuji Electric Co., Ltd.": "FELTY",
    "Canon Inc.": "CAJ",
    "Ricoh Company, Ltd.": "RICOY",
    "Nintendo Co., Ltd.": "NTDOY",
    "Sony Financial Holdings Inc.": "SNYFY",
    "Mitsubishi UFJ Financial Group, Inc.": "MUFG",
    "Sumitomo Mitsui Financial Group, Inc.": "SMFG",
    "Nomura Holdings, Inc.": "NMR",
    "Tokyo Electron Limited": "TOELY",
    "Advantest Corporation": "ATEYY",
    "Canon Inc.": "CAJ",
    "Nikon Corporation": "NINOY",
    "Tokyo Electron Limited": "TOELY",
    "Dai Nippon Printing Co., Ltd.": "DNPLY",
    "Rakuten, Inc.": "RKUNY",
    "Sony Group Corporation": "SONY",
    "Panasonic Corporation": "PCRFY",
    "Toshiba Corporation": "TOSYY",
    "Mitsubishi Corporation": "MSBHY",
    "Marubeni Corporation": "MARUY",
    "Sumitomo Corporation": "SSUMY",
    "Itochu Corporation": "ITOCY",
    "Sojitz Corporation": "SJIZF",
    "Toyota Tsusho Corporation": "TYHOF",
    "Mitsui & Co., Ltd.": "MITSY",
    "Sumitomo Mitsui Trust Holdings, Inc.": "SUTNY",
    "Mizuho Financial Group, Inc.": "MFG",
    "Nomura Holdings, Inc.": "NMR",
    "Daiwa Securities Group Inc.": "DSEEY",
    "Mitsubishi UFJ Financial Group, Inc.": "MUFG",
    "Chugai Pharmaceutical Co., Ltd.": "CHGCY",
    "Shionogi & Co., Ltd.": "SGIOY",
    "Daiichi Sankyo Company, Limited": "DSKYF",
    "Mitsubishi Tanabe Pharma Corporation": "MTZPY",
    "Takeda Pharmaceutical Company Limited": "TAK",
    "Astellas Pharma Inc.": "ALPMY",
    "Eisai Co., Ltd.": "ESALY",
    "Otsuka Holdings Co., Ltd.": "OTSKY",
    "Teijin Limited": "TINLY",
    "Toray Industries, Inc.": "TRYIY",
    "Mitsubishi Chemical Holdings Corporation": "MTLHY",
    "Sumitomo Chemical Co., Ltd.": "SOMMY",
    "Asahi Kasei Corporation": "AHKSY",
    "Nitto Denko Corporation": "NDEKY",
    "Sekisui Chemical Co., Ltd.": "SKSUY",
    "DIC Corporation": "DYFSF",
    "Showa Denko K.K.": "SHWDY",
    "Mitsui Chemicals, Inc.": "MITUY",
    "Kuraray Co., Ltd.": "KURRY",
    "Shin-Etsu Chemical Co., Ltd.": "SHECY",
    "Tosoh Corporation": "TOSCF",
    "JSR Corporation": "JSCPY",
    "Nissan Chemical Corporation": "NNCHY",
    "Fujifilm Holdings Corporation": "FUJIY",
    "Daiichi Sankyo Company, Limited": "DSKYF",
    "Asahi Glass Co., Ltd.": "ASGLY",
    "AGC Inc.": "ASGLY",
    "Sumitomo Electric Industries, Ltd.": "SMTOY",
    "Furukawa Electric Co., Ltd.": "FUWAY",
    "Fujitsu Limited": "FJTSY",
    "NEC Corporation": "NIPNF",
    "NTT DATA Corporation": "NTDTY",
    "Toshiba Corporation": "TOSYY",
    "Olympus Corporation": "OCPNY",
    "Renesas Electronics Corporation": "RNECY",
    "Advantest Corporation": "ATEYY",
    "Tokyo Electron Limited": "TOELY",
    "Shimadzu Corporation": "SHMDF",
    "Hitachi High-Tech Corporation": "HTHIF",
    "Nikon Corporation": "NINOY",
    "Keyence Corporation": "KYCCF",
    "Horiba, Ltd.": "HRIBF",
    "Yokogawa Electric Corporation": "YOKEY",
    "Nissin Electric Co., Ltd.": "NSNSY",
    "Epson": "SEKEY",
    "Daikin Industries, Ltd.": "DKILY",
    "Hitachi, Ltd.": "HTHIY",
    "Mitsubishi Electric Corporation": "MIELY",
    "Fujitsu General Ltd.": "FGELF",
    "Panasonic Corporation": "PCRFY",
    "Sony Corporation": "SNE",
    "Sharp Corporation": "SHCAY",
    "Toshiba Corporation": "TOSYY",
    "Fujifilm Corporation": "FUJIY",
    "Canon Inc.": "CAJ",
    "Ricoh Company, Ltd.": "RICOY",
    "Nikon Corporation": "NINOY",
    "Olympus Corporation": "OCPNY",
    "Fujitsu Limited": "FJTSY",
    "NEC Corporation": "NIPNF",
    "NTT DATA Corporation": "NTDTY",
    "Toshiba Corporation": "TOSYY",
    "Kyocera Corporation": "KYOCY",
    "Murata Manufacturing Co., Ltd.": "MRAAY",
    "TDK Corporation": "TTDKY",
    "Taiyo Yuden Co., Ltd.": "TYYHY",
    "Sony Corporation": "SNE",
    "Alps Alpine Co., Ltd.": "APELY",
    "Nidec Corporation": "NJDCY",
    "Minebea Mitsumi Inc.": "MNBEY",
    "Toshiba Corporation": "TOSYY",
    "Tokyo Electron Limited": "TOELY",
    "SCREEN Holdings Co., Ltd.": "DINRF",
    "Nikon Corporation": "NINOY",
    "Canon Inc.": "CAJ",
    "Ricoh Company, Ltd.": "RICOY",
    "Fujitsu Limited": "FJTSY",
    "NEC Corporation": "NIPNF",
    "Toshiba Corporation": "TOSYY",
    "Kyocera Corporation": "KYOCY",
    "Nidec Corporation": "NJDCY",
    "Seiko Epson Corporation": "SEKEY",
    "NTT DOCOMO, Inc.": "DCMYY",
    "KDDI Corporation": "KDDIY",
    "SoftBank Corp.": "SFTBY",
    "Sony Corporation": "SNE",
    "Nippon Telegraph and Telephone Corporation": "NTTYY",
    "Chunghwa Telecom Co., Ltd.": "CHT",
    "Singapore Telecommunications Limited": "SGAPY",
    "China Mobile Limited": "CHL",
    "China Telecom Corporation Limited": "CHA",
    "China Unicom (Hong Kong) Limited": "CHU",
    "Nippon Telegraph and Telephone Corporation": "NTTYY",
    "KDDI Corporation": "KDDIY",
    "SoftBank Corp.": "SFTBY",
    "NTT DOCOMO, Inc.": "DCMYY",
    "Nippon Telegraph and Telephone Corporation": "NTTYY",
    "KDDI Corporation": "KDDIY",
    "SoftBank Corp.": "SFTBY",
    "China Mobile Limited": "CHL",
    "China Telecom Corporation Limited": "CHA",
    "China Unicom (Hong Kong) Limited": "CHU",
    "KT Corporation": "KT",
    "SK Telecom Co., Ltd.": "SKM",
    "LG Uplus Corp.": "LGU+",
    "Nippon Telegraph and Telephone Corporation": "NTTYY",
    "KDDI Corporation": "KDDIY",
    "SoftBank Corp.": "SFTBY",
    "NTT DOCOMO, Inc.": "DCMYY",
    "China Mobile Limited": "CHL",
    "China Telecom Corporation Limited": "CHA",
    "China Unicom (Hong Kong) Limited": "CHU",
    "KT Corporation": "KT",
    "SK Telecom Co., Ltd.": "SKM",
    "LG Uplus Corp.": "LGU+",
    "China Mobile Limited": "CHL",
    "China Telecom Corporation Limited": "CHA",
    "China Unicom (Hong Kong) Limited": "CHU",
    "SK Hynix Inc.": "HXSCF",
    "Taiwan Semiconductor Manufacturing Company Limited": "TSM",
    "UMC": "UMC",
    "ASE Technology Holding Co., Ltd.": "ASX",
    "Samsung Electronics Co., Ltd.": "SSNLF",
    "LG Display Co., Ltd.": "LPL",
    "SK Innovation Co., Ltd.": "SKIVF",
    "Panasonic Corporation": "PCRFY",
    "Sony Corporation": "SNE",
    "Canon Inc.": "CAJ",
    "Ricoh Company, Ltd.": "RICOY",
    "Fujitsu Limited": "FJTSY",
    "NEC Corporation": "NIPNF",
    "NTT DATA Corporation": "NTDTY",
    "Toshiba Corporation": "TOSYY",
    "Kyocera Corporation": "KYOCY",
    "Seiko Epson Corporation": "SEKEY",
    "Hitachi, Ltd.": "HTHIY",
    "Fujifilm Corporation": "FUJIY",
    "Nikon Corporation": "NINOY",
    "Olympus Corporation": "OCPNY",
    "Pioneer Corporation": "PNCOY",
    "Sharp Corporation": "SHCAY",
    "Sony Corporation": "SNE",
    "DENSO Corporation": "DNZOY",
    "Aisin Seiki Co., Ltd.": "ASEKY",
    "Sumitomo Electric Industries, Ltd.": "SMTOY",
    "Omron Corporation": "OMRNY",
    "Yaskawa Electric Corporation": "YASKY",
    "Fanuc Corporation": "FANUY",
    "Mitsubishi Electric Corporation": "MIELY",
    "Mitsubishi Heavy Industries, Ltd.": "MHVYF",
    "Kawasaki Heavy Industries, Ltd.": "KWHIY",
    "IHI Corporation": "IHICY",
    "Komatsu Ltd.": "KMTUY",
    "Kobelco Construction Machinery Co., Ltd.": "KBSTY",
    "Hitachi Construction Machinery Co., Ltd.": "HTCMY",
    "Hino Motors, Ltd.": "HINOY",
    "Isuzu Motors Limited": "ISUZY",
    "Mazda Motor Corporation": "MZDAY",
    "Subaru Corporation": "FUJHY",
    "Mitsubishi Motors Corporation": "MMTOF",
    "Suzuki Motor Corporation": "SZKMY",
    "Toyota Motor Corporation": "TM",
    "Honda Motor Co., Ltd.": "HMC",
    "Nissan Motor Co., Ltd.": "NSANY",
    "Yamaha Motor Co., Ltd.": "YAMHY",
    "Kawasaki Heavy Industries, Ltd.": "KWHIY",
    "Bridgestone Corporation": "BRDCY",
    "Yokohama Rubber Co., Ltd.": "YORUY",
    "Toyo Tire Corporation": "TYOYY",
    "Sumitomo Rubber Industries, Ltd.": "SMTUF",
    "Mitsubishi Chemical Holdings Corporation": "MTLHY",
    "Toray Industries, Inc.": "TRYIY",
    "Asahi Kasei Corporation": "AHKSY",
    "DIC Corporation": "DYFSF",
    "Teijin Limited": "TINLY",
    "Nitto Denko Corporation": "NDEKY",
    "JSR Corporation": "JSCPY",
    "Daikin Industries, Ltd.": "DKILY",
    "Hitachi Chemical Company, Ltd.": "HCHMY",
    "Kuraray Co., Ltd.": "KURRY",
    "Shin-Etsu Chemical Co., Ltd.": "SHECY",
    "Showa Denko K.K.": "SHWDY",
    "Sumitomo Chemical Co., Ltd.": "SOMMY",
    "Mitsui Chemicals, Inc.": "MITUY",
    "Tosoh Corporation": "TOSCF",
    "Idemitsu Kosan Co., Ltd.": "IDKOY",
    "JXTG Holdings, Inc.": "JXHLY",
    "ENEOS Holdings, Inc.": "JXHLY",
    "ENEOS Holdings, Inc.": "JXHLY",
    "ENEOS Holdings, Inc.": "JXHLY",
    "ENEOS Holdings, Inc.": "JXHLY",
    "Tokyo Electric Power Company Holdings, Inc.": "TKECY",
    "Kansai Electric Power Co., Inc.": "KAEPY",
    "Chubu Electric Power Co., Inc.": "CHUEF",
    "Tohoku Electric Power Co., Inc.": "TOEUF",
    "Hokkaido Electric Power Company, Incorporated": "HKECY",
    "Kyushu Electric Power Co., Inc.": "KYSEY",
    "Hokuriku Electric Power Company": "HRKUF",
    "Chugoku Electric Power Company": "CGKEY",
    "Shikoku Electric Power Company, Incorporated": "SHECF",
    "Mitsubishi Electric Corporation": "MIELY",
    "Sony Corporation": "SNE",
    "Panasonic Corporation": "PCRFY",
    "Sharp Corporation": "SHCAY",
    "Fujitsu Limited": "FJTSY",
    "NEC Corporation": "NIPNF",
    "Hitachi, Ltd.": "HTHIY",
    "Toshiba Corporation": "TOSYY",
    "Olympus Corporation": "OCPNY",
    "Ricoh Company, Ltd.": "RICOY",
    "Canon Inc.": "CAJ",
    "Seiko Epson Corporation": "SEKEY",
    "Nikon Corporation": "NINOY",
    "Fujifilm Corporation": "FUJIY",
    "Hoya Corporation": "HOCPY",
    "Olympus Corporation": "OCPNY",
    "Rohm Co., Ltd.": "ROHCY",
    "Kyocera Corporation": "KYOCY",
    "TDK Corporation": "TTDKY",
    "Sony Corporation": "SNE",
    "Nidec Corporation": "NJDCY",
    "Advantest Corporation": "ATEYY",
    "Tokyo Electron Limited": "TOELY",
    "Canon Inc.": "CAJ",
    "Nikon Corporation": "NINOY",
    "Olympus Corporation": "OCPNY",
    "Fujifilm Corporation": "FUJIY",
    "Hoya Corporation": "HOCPY",
    "Olympus Corporation": "OCPNY",
    "Rohm Co., Ltd.": "ROHCY",
    "Kyocera Corporation": "KYOCY",
    "TDK Corporation": "TTDKY",
    "Sony Corporation": "SNE",
    "Nidec Corporation": "NJDCY",
    "Advantest Corporation": "ATEYY",
    "Tokyo Electron Limited": "TOELY",
    "Canon Inc.": "CAJ",
    "Nikon Corporation": "NINOY",
    "Olympus Corporation": "OCPNY",
    "Fujifilm Corporation": "FUJIY",
    "Hoya Corporation": "HOCPY",
    "Olympus Corporation": "OCPNY",
    "Rohm Co., Ltd.": "ROHCY",
    "Kyocera Corporation": "KYOCY",
    "TDK Corporation": "TTDKY",
    "Sony Corporation": "SNE",
    "Nidec Corporation": "NJDCY",
    "Advantest Corporation": "ATEYY",
    "Tokyo Electron Limited": "TOELY",
    "Canon Inc.": "CAJ",
    "Nikon Corporation": "NINOY",
    "Olympus Corporation": "OCPNY",
    "Fujifilm Corporation": "FUJIY",
    "Hoya Corporation": "HOCPY",
    "Olympus Corporation": "OCPNY",
    "Rohm Co., Ltd.": "ROHCY",
    "Kyocera Corporation": "KYOCY",
    "TDK Corporation": "TTDKY",
    "Sony Corporation": "SNE",
    "Nidec Corporation": "NJDCY",
    "Advantest Corporation": "ATEYY",
    "Tokyo Electron Limited": "TOELY",
    "Sony Corporation": "SNE",
    "Panasonic Corporation": "PCRFY",
    "Hitachi, Ltd.": "HTHIY",
    "Toshiba Corporation": "TOSYY",
    "Fujitsu Limited": "FJTSY",
    "NEC Corporation": "NIPNF",
    "Canon Inc.": "CAJ",
    "Ricoh Company, Ltd.": "RICOY",
    "Olympus Corporation": "OCPNY",
    "Nikon Corporation": "NINOY",
    "Fujifilm Corporation": "FUJIY",
    "Seiko Epson Corporation": "SEKEY",
    "Nissan Motor Co., Ltd.": "NSANY",
    "Mitsubishi Motors Corporation": "MMTOF",
    "Subaru Corporation": "FUJHY",
    "Suzuki Motor Corporation": "SZKMY",
    "Isuzu Motors Limited": "ISUZY",
    "Mazda Motor Corporation": "MZDAY",
    "Toyota Motor Corporation": "TM",
    "Honda Motor Co., Ltd.": "HMC",
    "Yamaha Motor Co., Ltd.": "YAMHY",
    "Mitsubishi Heavy Industries, Ltd.": "MHVYF",
    "Kawasaki Heavy Industries, Ltd.": "KWHIY",
    "Fuji Electric Co., Ltd.": "FELTY",
    "Hitachi Zosen Corporation": "HTZNY",
    "JFE Holdings, Inc.": "JFEEF",
    "Nippon Steel Corporation": "NISTY",
    "JFE Holdings, Inc.": "JFEEF",
    "Kobe Steel, Ltd.": "KBSTY",
    "Sumitomo Metal Industries, Ltd.": "SMMLY",
    "Nisshin Steel Co., Ltd.": "NSSTY",
    "Nucor Corporation": "NUE",
    "United States Steel Corporation": "X",
    "Steel Dynamics, Inc.": "STLD",
    "POSCO": "PKX",
    "Nippon Steel Corporation": "NISTY",
    "JFE Holdings, Inc.": "JFEEF",
    "Nucor Corporation": "NUE",
    "United States Steel Corporation": "X",
    "Steel Dynamics, Inc.": "STLD",
    "POSCO": "PKX",
    "Gerdau S.A.": "GGB",
    "Ternium S.A.": "TX",
    "ArcelorMittal": "MT",
    "Vale S.A.": "VALE",
    "Rio Tinto Group": "RIO",
    "BHP": "BHP",
    "Freeport-McMoRan Inc.": "FCX",
    "Alcoa Corporation": "AA",
    "Norsk Hydro ASA": "NHYDY",
    "Vedanta Limited": "VEDL",
    "BHP": "BHP",
    "Rio Tinto Group": "RIO",
    "Anglo American plc": "NGLOY",
    "Mitsubishi Corporation": "MSBHY",
    "Glencore plc": "GLNCY",
    "BHP": "BHP",
    "Rio Tinto Group": "RIO",
    "Vale S.A.": "VALE",
    "BHP": "BHP",
    "Rio Tinto Group": "RIO",
    "Vale S.A.": "VALE",
    "BHP": "BHP",
    "Rio Tinto Group": "RIO",
    "Vale S.A.": "VALE",
    "BHP": "BHP",
    "Rio Tinto Group": "RIO",
    "Vale S.A.": "VALE",
    "Goldcorp Inc.": "GG",
    "Newmont Corporation": "NEM",
    "Barrick Gold Corporation": "GOLD",
    "AngloGold Ashanti Limited": "AU",
    "Gold Fields Limited": "GFI",
    "Kinross Gold Corporation": "KGC",
    "Agnico Eagle Mines Limited": "AEM",
    "Yamana Gold Inc.": "AUY",
    "Eldorado Gold Corporation": "EGO",
    "IAMGOLD Corporation": "IAG",
    "Alamos Gold Inc.": "AGI",
    "Newcrest Mining Limited": "NCMGY",
    "Northern Star Resources Limited": "NSTGY",
    "Evolution Mining Limited": "CAHPF",
    "Barrick Gold Corporation": "GOLD",
    "Newmont Corporation": "NEM",
    "AngloGold Ashanti Limited": "AU",
    "Gold Fields Limited": "GFI",
    "Kinross Gold Corporation": "KGC",
    "Agnico Eagle Mines Limited": "AEM",
    "Yamana Gold Inc.": "AUY",
    "Barrick Gold Corporation": "GOLD",
    "Newmont Corporation": "NEM",
    "AngloGold Ashanti Limited": "AU",
    "Gold Fields Limited": "GFI",
    "Kinross Gold Corporation": "KGC",
    "Agnico Eagle Mines Limited": "AEM",
    "Yamana Gold Inc.": "AUY",
    "Eldorado Gold Corporation": "EGO",
    "IAMGOLD Corporation": "IAG"
}