productToCompanyTicker = {
    'nike air force 1': 'nke',
    'nike air jordan': 'nke',
    'nike air max': 'nke',
    'nike air zoom': 'nke',
    'nike blazer': 'nke',
    'nike cortez': 'nke',
    'nike dunk': 'nke',
    'nike react': 'nke',
    'starbucks coffee': 'sbux',
    'starbucks espresso': 'sbux',
    'starbucks latte': 'sbux',
    'starbucks frappuccino': 'sbux',
    'starbucks cappuccino': 'sbux',
    'starbucks macchiato': 'sbux',
    'starbucks refreshers': 'sbux',
    'starbucks tea': 'sbux',
    'the coca-cola company': 'ko',
    'coca-cola classic': 'ko',
    'diet coke': 'ko',
    'coca-cola zero sugar': 'ko',
    'sprite': 'ko',
    'fanta': 'ko',
    'minute maid': 'ko',
    'dasani': 'ko',
    'powerade': 'ko',
    'monster energy': 'mnst',
    'red bull': 'rblx',
    'rockstar energy': 'pep',
    '3m': 'mmm',
    'post-it': 'mmm',
    'scotch': 'mmm',
    'command': 'mmm',
    'futuro': 'mmm',
    'nexcare': 'mmm',
    'lysol': 'rbgly',
    'air wick': 'rbgly',
    'dettol': 'rbgly',
    'finish': 'rbgly',
    'veet': 'rbgly',
    'durex': 'rbgly',
    'clearasil': 'rbgly',
    'gaviscon': 'rbgly',
    'strepsils': 'rbgly',
    'enfamil': 'rbgly',
    'nutramigen': 'rbgly',
    'polyvisol': 'rbgly',
    'centrum': 'rbgly',
    'caltrate': 'rbgly',
    'emergen-c': 'rbgly',
    'mucinex': 'rbgly',
    'scholl': 'rbgly',
    'frenchs': 'rbgly',
    'franks redhot': 'rbgly',
    'old el paso': 'gis',
    'betty crocker': 'gis',
    'haagen-dazs': 'gis',
    'cascadian farm': 'gis',
    'nature valley': 'gis',
    'pillsbury': 'gis',
    'fiber one': 'gis',
    'cheerios': 'gis',
    'cinnamon toast crunch': 'gis',
    'tide': 'pg',
    'bounty': 'pg',
    'downy': 'pg',
    'charmin': 'pg',
    'gillette': 'pg',
    'oral-b': 'pg',
    'pampers': 'pg',
    'always': 'pg',
    'febreze': 'pg',
    'swiffer': 'pg',
    'dawn': 'pg',
    'olay': 'pg',
    'head & shoulders': 'pg',
    'herbal essences': 'pg',
    'vicks': 'pg',
    'crest': 'pg',
    'mr. clean': 'pg',
    'cascade': 'pg',
    'braun': 'pg',
    'ariel': 'pg',
    'pantene': 'pg',
    'ivory': 'pg',
    'luvs': 'pg',
    'whisper': 'pg',
    'metamucil': 'pg',
    'pepto-bismol': 'pg',
    'tampax': 'pg',
    'fixodent': 'pg',
    'ace': 'pg',
    'gain': 'pg',
    'nice n easy': 'pg',
    'wella': 'pg',
    'clairol': 'pg',
    'ora-id': 'pg',
    'hugo boss': 'pg',
    'sk-ii': 'pg',
    'venus': 'pg',
    'scope': 'pg',
    'nurofen': 'rbgly',
    'star wars': 'dis',
    'marvel': 'dis',
    'disney+': 'dis',
    'espn': 'dis',
    'pixar': 'dis',
    'fox': 'dis',
    'abc': 'dis',
    'national geographic': 'dis',
    'hulu': 'dis',
    'lucasfilm': 'dis',
    'the walt disney company': 'dis',
    'iphone': 'aapl',
    'ipad': 'aapl',
    'macbook': 'aapl',
    'imac': 'aapl',
    'apple watch': 'aapl',
    'airpods': 'aapl',
    'apple tv': 'aapl',
    'homepod': 'aapl',
    'icloud': 'aapl',
    'itunes': 'aapl',
    'apple music': 'aapl',
    'apple pay': 'aapl',
    'apple arcade': 'aapl',
    'apple fitness+': 'aapl',
    'apple news+': 'aapl',
    'google pixel': 'googl',
    'google pixelbook': 'googl',
    'google nest': 'googl',
    'google home': 'googl',
    'google chromecast': 'googl',
    'google wifi': 'googl',
    'google stadia': 'googl',
    'google meet': 'googl',
    'google workspace': 'googl',
    'chromebook': 'googl',
    'android': 'googl',
    'youtube music': 'googl',
    'google fit': 'googl',
    'google photos': 'googl',
    'google lens': 'googl',
    'google earth': 'googl',
    'google translate': 'googl',
    'google assistant': 'googl',
    'amazon echo': 'amzn',
    'fire tv': 'amzn',
    'kindle': 'amzn',
    'ring': 'amzn',
    'blink': 'amzn',
    'amazon basics': 'amzn',
    'amazon fresh': 'amzn',
    'whole foods market': 'amzn',
    'audible': 'amzn',
    'amazon prime video': 'amzn',
    'amazon prime music': 'amzn',
    'amazon web services': 'amzn',
    'amazon kindle': 'amzn',
    'amazon fire tablet': 'amzn',
    'amazon fire tv stick': 'amzn',
    'amazon fire tv cube': 'amzn',
    'amazon kindle fire': 'amzn',
    'amazon alexa': 'amzn',
    'amazon luna': 'amzn',
    'microsoft surface': 'msft',
    'microsoft surface pro': 'msft',
    'microsoft surface laptop': 'msft',
    'microsoft surface studio': 'msft',
    'microsoft surface go': 'msft',
    'microsoft surface book': 'msft',
    'microsoft xbox': 'msft',
    'microsoft xbox series x': 'msft',
    'microsoft xbox series s': 'msft',
    'microsoft xbox game pass': 'msft',
    'microsoft office': 'msft',
    'microsoft office 365': 'msft',
    'microsoft word': 'msft',
    'microsoft excel': 'msft',
    'microsoft powerpoint': 'msft',
    'microsoft outlook': 'msft',
    'microsoft teams': 'msft',
    'microsoft azure': 'msft',
    'microsoft dynamics': 'msft',
    'microsoft sql server': 'msft',
    'microsoft edge': 'msft',
    'microsoft bing': 'msft',
    'microsoft onedrive': 'msft',
    'microsoft onenote': 'msft',
    'microsoft skype': 'msft',
    'microsoft visio': 'msft',
    'microsoft access': 'msft',
    'microsoft publisher': 'msft',
    'microsoft project': 'msft',
    'microsoft stream': 'msft',
    'microsoft power bi': 'msft',
    'microsoft powerapps': 'msft',
    'microsoft flow': 'msft',
    'microsoft windows': 'msft',
    'microsoft windows 10': 'msft',
    'microsoft windows 11': 'msft',
    'microsoft windows defender': 'msft',
    'microsoft windows server': 'msft',
    'microsoft windows terminal': 'msft',
    'microsoft visual studio': 'msft',
    'microsoft visual studio code': 'msft',
    'microsoft .net': 'msft',
    'microsoft .net core': 'msft',
    'microsoft sql server management studio': 'msft',
    'microsoft sql server reporting services': 'msft',
    'microsoft sql server analysis services': 'msft',
    'microsoft sql server integration services': 'msft',
    'microsoft sql server data tools': 'msft',
    'microsoft sql server compact': 'msft',
    'microsoft sql server express': 'msft',
    'microsoft sql server enterprise': 'msft',
    'microsoft sql server standard': 'msft',
    'microsoft sql server business intelligence': 'msft',
    'microsoft sql server developer': 'msft',
    'microsoft sql server web': 'msft',
    'microsoft sql server mobile': 'msft',
    'microsoft sql server parallel data warehouse': 'msft',
    'microsoft sql server big data clusters': 'msft',
    'microsoft sql server machine learning services': 'msft',
    'microsoft sql server azure': 'msft',
    'microsoft sql server cosmos db': 'msft',
    'microsoft sql server data lake': 'msft',
    'microsoft sql server power bi': 'msft',
    'microsoft sql server synapse analytics': 'msft',
    'microsoft sql server streaminsight': 'msft',
    'microsoft sql server master data services': 'msft',
    'microsoft sql server service broker': 'msft',
    'microsoft sql server full-text search': 'msft',
    'microsoft sql server notification services': 'msft',
    'microsoft sql server replication': 'msft',
    'microsoft sql server data quality services': 'msft',
    'microsoft sql server polybase': 'msft',
    'microsoft sql server stretch database': 'msft',
}
