stockSymbole = {
    # indexes
    "s&p 500": "^gspc",
    "dow jones industrial average": "^dji",
    "nasdaq composite": "^ixic",
    "ftse 100": "^ftse",
    "dax": "^gdaxi",
    "cac 40": "^fchi",
    "nikkei 225": "^n225",
    "hang seng index": "^hsi",
    "s&p/asx 200": "^axjo",
    "shanghai composite": "^ssec",
    "euro stoxx 50": "^stoxx50e",
    "nifty 50": "^nsei",
    "sensex": "^bsesn",
    "ftse mib": "^ftsemib.mi",
    "kospi": "^ks11",
    "taiwan weighted": "^twii",
    "s&p/tsx composite": "^gsptse",
    "bovespa": "^bvsp",
    "ipc mexico": "^mxx",
    "ftse bursa malaysia klci": "^klse",
    "s&p/nzx 50": "^nz50",
    "s&p/asx 200": "^axjo",
    "jakarta composite": "^jkse",
    "straits times index": "^sti",
    "tsec weighted index": "^twii",
    "psi 20": "^psi20",
    "moex russia index": "^imoex",
    "athex composite share price index": "^atg",
    "ta-35 index": "^ta35",
    "iseq overall": "^iseq",
    "ibex 35": "^ibex",
    "ftse aim all-share index": "^ftai",
    "kase": "^kase",
    "idx composite": "^jkse",
    "bist 100": "^xu100",
    "ta-125": "^ta125.ta",
    "bux budapest stock index": "^bux",
    "nairobi securities exchange 20 share index": "^nse20",
    "jamaica stock exchange": "^jmse",
    "bahrain all share index": "^bax",
    "s&p 500 vix": "^vix",

    # companies
    "apple": "aapl",
    "microsoft": "msft",
    "amazon": "amzn",
    "alphabet": "googl",
    "facebook": "fb",
    "tesla": "tsla",
    "johnson & johnson": "jnj",
    "jpmorgan chase": "jpm",
    "walmart": "wmt",
    "procter & gamble": "pg",
    "bank of america": "bac",
    "netflix": "nflx",
    "visa": "v",
    "mastercard": "ma",
    "intel": "intc",
    "cisco": "csco",
    "boeing": "ba",
    "general electric": "ge",
    "exxon mobil": "xom",
    "chevron": "cvx",
    "ibm": "ibm",
    "coca-cola": "ko",
    "pepsico": "pep",
    "mcdonald's": "mcd",
    "disney": "dis",
    "at&t": "t",
    "verizon": "vz",
    "nvidia": "nvda",
    "amd": "amd",
    "salesforce": "crm",
    "adobe": "adbe",
    "oracle": "orcl",
    "home depot": "hd",
    "lowe's": "low",
    "ibm": "ibm",
    "intel": "intc",
    "general motors": "gm",
    "ford motor company": "f",
    "twitter": "twtr",
    "snap inc.": "snap",
    "uber technologies": "uber",
    "lyft": "lyft",
    "alibaba group": "baba",
    "tencent holdings": "tcehy",
    "berkshire hathaway": "brk.a",
    "sony": "sony",
    "nintendo": "ntdoy",
    "mitsubishi": "msbhy",
    "hyundai motor": "hymtf",
    "samsung electronics": "ssnlf",
    "sony corporation": "sne",
    "toyota motor": "tm",
    "honda motor": "hmc",
    "nestle": "nsrgy",
    "unilever": "ul",
    "nike": "nke",
    "adidas": "addyy",
    "lvmh moet hennessy louis vuitton se": "lvmuy",
    "ferrari": "race",
    "pfizer": "pfe",
    "merck & co.": "mrk",
    "bristol-myers squibb": "bmy",
    "glaxosmithkline": "gsk",
    "novartis ag": "nvs",
    "roche holding ag": "rog",
    "sanofi": "sny",
    "astrazeneca": "azn",
    "abbvie inc.": "abbv",
    "gilead sciences": "gild",
    "biogen inc.": "biib",
    "vertex pharmaceuticals": "vrtx",
    "regeneron pharmaceuticals": "regn",
    "eli lilly and company": "lly",
    "bayer ag": "bayry",
    "siemens ag": "siegy",
    "bmw ag": "bmwyy",
    "daimler ag": "ddaif",
    "volkswagen ag": "vwagy",
    "audi ag": "audvf",
    "porsche se": "poahy",
    "basf se": "basfy",
    "lufthansa group": "dlaky",
    "deutsche post ag": "dpsgy",
    "deutsche bank ag": "db",
    "allianz se": "alizf",
    "munich re": "murgy",
    "bayerische motoren werke ag": "bmwyy",
    "thyssenkrupp ag": "tyekf",
    "volkswagen group": "vwagy",
    "continental ag": "cttay",
    "airbus se": "eadsy",
    "banco santander": "san",
    "bbva": "bbva",
    "iberdrola": "ibdry",
    "telefonica": "tef",
    "inditex": "idexy",
    "repsol": "repyy",
    "eni spa": "e",
    "totalenergies": "tte",
    "royal dutch shell": "rds.a",
    "bp plc": "bp",
    "nokia corporation": "nok",
    "ericsson": "eric",
    "accenture": "acn",
    "capgemini": "cap",
    "infosys": "infy",
    "tata consultancy services": "tcs",
    "wipro": "wit",
    "cognizant": "ctsh",
    "hewlett packard enterprise": "hpe",
    "dell technologies": "dell",
    "lenovo group": "lnvgy",
    "sony corporation": "sne",
    "panasonic corporation": "pcrfy",
    "hitachi ltd.": "hthiy",
    "mitsubishi electric corporation": "miely",
    "fuji electric co., ltd.": "felty",
    "canon inc.": "caj",
    "ricoh company, ltd.": "ricoy",
    "nintendo co., ltd.": "ntdoy",
    "sony financial holdings inc.": "snyfy",
    "mitsubishi ufj financial group, inc.": "mufg",
    "sumitomo mitsui financial group, inc.": "smfg",
    "nomura holdings, inc.": "nmr",
    "tokyo electron limited": "toely",
    "advantest corporation": "ateyy",
    "canon inc.": "caj",
    "nikon corporation": "ninoy",
    "tokyo electron limited": "toely",
    "dai nippon printing co., ltd.": "dnply",
    "rakuten, inc.": "rkuny",
    "sony group corporation": "sony",
    "panasonic corporation": "pcrfy",
    "toshiba corporation": "tosyy",
    "mitsubishi corporation": "msbhy",
    "marubeni corporation": "maruy",
    "sumitomo corporation": "ssumy",
    "itochu corporation": "itocy",
    "sojitz corporation": "sjizf",
    "toyota tsusho corporation": "tyhof",
    "mitsui & co., ltd.": "mitsy",
    "sumitomo mitsui trust holdings, inc.": "sutny",
    "mizuho financial group, inc.": "mfg",
    "nomura holdings, inc.": "nmr",
    "daiwa securities group inc.": "dseey",
    "mitsubishi ufj financial group, inc.": "mufg",
    "chugai pharmaceutical co., ltd.": "chgcy",
    "shionogi & co., ltd.": "sgioy",
    "daiichi sankyo company, limited": "dskyf",
    "mitsubishi tanabe pharma corporation": "mtzpy",
    "takeda pharmaceutical company limited": "tak",
    "astellas pharma inc.": "alpmy",
    "eisai co., ltd.": "esaly",
    "otsuka holdings co., ltd.": "otsky",
    "teijin limited": "tinly",
    "toray industries, inc.": "tryiy",
    "mitsubishi chemical holdings corporation": "mtlhy",
    "sumitomo chemical co., ltd.": "sommy",
    "asahi kasei corporation": "ahksy",
    "nitto denko corporation": "ndeky",
    "sekisui chemical co., ltd.": "sksuy",
    "dic corporation": "dyfsf",
    "showa denko k.k.": "shwdy",
    "mitsui chemicals, inc.": "mituy",
    "kuraray co., ltd.": "kurry",
    "shin-etsu chemical co., ltd.": "shecy",
    "tosoh corporation": "toscf",
    "jsr corporation": "jscpy",
    "nissan chemical corporation": "nnchy",
    "fujifilm holdings corporation": "fujiy",
    "daiichi sankyo company, limited": "dskyf",
    "asahi glass co., ltd.": "asgly",
    "agc inc.": "asgly",
    "sumitomo electric industries, ltd.": "smtoy",
    "furukawa electric co., ltd.": "fuway",
    "fujitsu limited": "fjtsy",
    "nec corporation": "nipnf",
    "ntt data corporation": "ntdty",
    "toshiba corporation": "tosyy",
    "olympus corporation": "ocpny",
    "renesas electronics corporation": "rnecy",
    "advantest corporation": "ateyy",
    "tokyo electron limited": "toely",
    "shimadzu corporation": "shmdf",
    "hitachi high-tech corporation": "hthif",
    "nikon corporation": "ninoy",
    "keyence corporation": "kyccf",
    "horiba, ltd.": "hribf",
    "yokogawa electric corporation": "yokey",
    "nissin electric co., ltd.": "nsnsy",
    "epson": "sekey",
    "daikin industries, ltd.": "dkily",
    "hitachi, ltd.": "hthiy",
    "mitsubishi electric corporation": "miely",
    "fujitsu general ltd.": "fgelf",
    "panasonic corporation": "pcrfy",
    "sony corporation": "sne",
    "sharp corporation": "shcay",
    "toshiba corporation": "tosyy",
    "fujifilm corporation": "fujiy",
    "canon inc.": "caj",
    "ricoh company, ltd.": "ricoy",
    "nikon corporation": "ninoy",
    "olympus corporation": "ocpny",
    "fujitsu limited": "fjtsy",
    "nec corporation": "nipnf",
    "ntt data corporation": "ntdty",
    "toshiba corporation": "tosyy",
    "kyocera corporation": "kyocy",
    "murata manufacturing co., ltd.": "mraay",
    "tdk corporation": "ttdky",
    "taiyo yuden co., ltd.": "tyyhy",
    "sony corporation": "sne",
    "alps alpine co., ltd.": "apely",
    "nidec corporation": "njdcy",
    "minebea mitsumi inc.": "mnbey",
    "toshiba corporation": "tosyy",
    "tokyo electron limited": "toely",
    "screen holdings co., ltd.": "dinrf",
    "nikon corporation": "ninoy",
    "canon inc.": "caj",
    "ricoh company, ltd.": "ricoy",
    "fujitsu limited": "fjtsy",
    "nec corporation": "nipnf",
    "toshiba corporation": "tosyy",
    "kyocera corporation": "kyocy",
    "nidec corporation": "njdcy",
    "seiko epson corporation": "sekey",
    "ntt docomo, inc.": "dcmyy",
    "kddi corporation": "kddiy",
    "softbank corp.": "sftby",
    "sony corporation": "sne",
    "nippon telegraph and telephone corporation": "nttyy",
    "chunghwa telecom co., ltd.": "cht",
    "singapore telecommunications limited": "sgapy",
    "china mobile limited": "chl",
    "china telecom corporation limited": "cha",
    "china unicom (hong kong) limited": "chu",
    "nippon telegraph and telephone corporation": "nttyy",
    "kddi corporation": "kddiy",
    "softbank corp.": "sftby",
    "ntt docomo, inc.": "dcmyy",
    "nippon telegraph and telephone corporation": "nttyy",
    "kddi corporation": "kddiy",
    "softbank corp.": "sftby",
    "china mobile limited": "chl",
    "china telecom corporation limited": "cha",
    "china unicom (hong kong) limited": "chu",
    "kt corporation": "kt",
    "sk telecom co., ltd.": "skm",
    "lg uplus corp.": "lgu+",
    "nippon telegraph and telephone corporation": "nttyy",
    "kddi corporation": "kddiy",
    "softbank corp.": "sftby",
    "ntt docomo, inc.": "dcmyy",
    "china mobile limited": "chl",
    "china telecom corporation limited": "cha",
    "china unicom (hong kong) limited": "chu",
    "kt corporation": "kt",
    "sk telecom co., ltd.": "skm",
    "lg uplus corp.": "lgu+",
    "china mobile limited": "chl",
    "china telecom corporation limited": "cha",
    "china unicom (hong kong) limited": "chu",
    "sk hynix inc.": "hxscf",
    "taiwan semiconductor manufacturing company limited": "tsm",
    "umc": "umc",
    "ase technology holding co., ltd.": "asx",
    "samsung electronics co., ltd.": "ssnlf",
    "lg display co., ltd.": "lpl",
    "sk innovation co., ltd.": "skivf",
    "panasonic corporation": "pcrfy",
    "sony corporation": "sne",
    "canon inc.": "caj",
    "ricoh company, ltd.": "ricoy",
    "fujitsu limited": "fjtsy",
    "nec corporation": "nipnf",
    "ntt data corporation": "ntdty",
    "toshiba corporation": "tosyy",
    "kyocera corporation": "kyocy",
    "seiko epson corporation": "sekey",
    "hitachi, ltd.": "hthiy",
    "fujifilm corporation": "fujiy",
    "nikon corporation": "ninoy",
    "olympus corporation": "ocpny",
    "pioneer corporation": "pncoy",
    "sharp corporation": "shcay",
    "sony corporation": "sne",
    "denso corporation": "dnzoy",
    "aisin seiki co., ltd.": "aseky",
    "sumitomo electric industries, ltd.": "smtoy",
    "omron corporation": "omrny",
    "yaskawa electric corporation": "yasky",
    "fanuc corporation": "fanuy",
    "mitsubishi electric corporation": "miely",
    "mitsubishi heavy industries, ltd.": "mhvyf",
    "kawasaki heavy industries, ltd.": "kwhiy",
    "ihi corporation": "ihicy",
    "komatsu ltd.": "kmtuy",
    "kobelco construction machinery co., ltd.": "kbsty",
    "hitachi construction machinery co., ltd.": "htcmy",
    "hino motors, ltd.": "hinoy",
    "isuzu motors limited": "isuzy",
    "mazda motor corporation": "mzday",
    "subaru corporation": "fujhy",
    "mitsubishi motors corporation": "mmtof",
    "suzuki motor corporation": "szkmy",
    "toyota motor corporation": "tm",
    "honda motor co., ltd.": "hmc",
    "nissan motor co., ltd.": "nsany",
    "yamaha motor co., ltd.": "yamhy",
    "kawasaki heavy industries, ltd.": "kwhiy",
    "bridgestone corporation": "brdcy",
    "yokohama rubber co., ltd.": "yoruy",
    "toyo tire corporation": "tyoyy",
    "sumitomo rubber industries, ltd.": "smtuf",
    "mitsubishi chemical holdings corporation": "mtlhy",
    "toray industries, inc.": "tryiy",
    "asahi kasei corporation": "ahksy",
    "dic corporation": "dyfsf",
    "teijin limited": "tinly",
    "nitto denko corporation": "ndeky",
    "jsr corporation": "jscpy",
    "daikin industries, ltd.": "dkily",
    "hitachi chemical company, ltd.": "hchmy",
    "kuraray co., ltd.": "kurry",
    "shin-etsu chemical co., ltd.": "shecy",
    "showa denko k.k.": "shwdy",
    "sumitomo chemical co., ltd.": "sommy",
    "mitsui chemicals, inc.": "mituy",
    "tosoh corporation": "toscf",
    "idemitsu kosan co., ltd.": "idkoy",
    "jxtg holdings, inc.": "jxhly",
    "eneos holdings, inc.": "jxhly",
    "eneos holdings, inc.": "jxhly",
    "eneos holdings, inc.": "jxhly",
    "eneos holdings, inc.": "jxhly",
    "tokyo electric power company holdings, inc.": "tkecy",
    "kansai electric power co., inc.": "kaepy",
    "chubu electric power co., inc.": "chuef",
    "tohoku electric power co., inc.": "toeuf",
    "hokkaido electric power company, incorporated": "hkecy",
    "kyushu electric power co., inc.": "kysey",
    "hokuriku electric power company": "hrkuf",
    "chugoku electric power company": "cgkey",
    "shikoku electric power company, incorporated": "shecf",
    "mitsubishi electric corporation": "miely",
    "sony corporation": "sne",
    "panasonic corporation": "pcrfy",
    "sharp corporation": "shcay",
    "fujitsu limited": "fjtsy",
    "nec corporation": "nipnf",
    "hitachi, ltd.": "hthiy",
    "toshiba corporation": "tosyy",
    "olympus corporation": "ocpny",
    "ricoh company, ltd.": "ricoy",
    "canon inc.": "caj",
    "seiko epson corporation": "sekey",
    "nikon corporation": "ninoy",
    "fujifilm corporation": "fujiy",
    "hoya corporation": "hocpy",
    "olympus corporation": "ocpny",
    "rohm co., ltd.": "rohcy",
    "kyocera corporation": "kyocy",
    "tdk corporation": "ttdky",
    "sony corporation": "sne",
    "nidec corporation": "njdcy",
    "advantest corporation": "ateyy",
    "tokyo electron limited": "toely",
    "canon inc.": "caj",
    "nikon corporation": "ninoy",
    "olympus corporation": "ocpny",
    "fujifilm corporation": "fujiy",
    "hoya corporation": "hocpy",
    "olympus corporation": "ocpny",
    "rohm co., ltd.": "rohcy",
    "kyocera corporation": "kyocy",
    "tdk corporation": "ttdky",
    "sony corporation": "sne",
    "nidec corporation": "njdcy",
    "advantest corporation": "ateyy",
    "tokyo electron limited": "toely",
    "canon inc.": "caj",
    "nikon corporation": "ninoy",
    "olympus corporation": "ocpny",
    "fujifilm corporation": "fujiy",
    "hoya corporation": "hocpy",
    "olympus corporation": "ocpny",
    "rohm co., ltd.": "rohcy",
    "kyocera corporation": "kyocy",
    "tdk corporation": "ttdky",
    "sony corporation": "sne",
    "nidec corporation": "njdcy",
    "advantest corporation": "ateyy",
    "tokyo electron limited": "toely",
    "canon inc.": "caj",
    "nikon corporation": "ninoy",
    "olympus corporation": "ocpny",
    "fujifilm corporation": "fujiy",
    "hoya corporation": "hocpy",
    "olympus corporation": "ocpny",
    "rohm co., ltd.": "rohcy",
    "kyocera corporation": "kyocy",
    "tdk corporation": "ttdky",
    "sony corporation": "sne",
    "nidec corporation": "njdcy",
    "advantest corporation": "ateyy",
    "tokyo electron limited": "toely",
    "sony corporation": "sne",
    "panasonic corporation": "pcrfy",
    "hitachi, ltd.": "hthiy",
    "toshiba corporation": "tosyy",
    "fujitsu limited": "fjtsy",
    "nec corporation": "nipnf",
    "canon inc.": "caj",
    "ricoh company, ltd.": "ricoy",
    "olympus corporation": "ocpny",
    "nikon corporation": "ninoy",
    "fujifilm corporation": "fujiy",
    "seiko epson corporation": "sekey",
    "nissan motor co., ltd.": "nsany",
    "mitsubishi motors corporation": "mmtof",
    "subaru corporation": "fujhy",
    "suzuki motor corporation": "szkmy",
    "isuzu motors limited": "isuzy",
    "mazda motor corporation": "mzday",
    "toyota motor corporation": "tm",
    "honda motor co., ltd.": "hmc",
    "yamaha motor co., ltd.": "yamhy",
    "mitsubishi heavy industries, ltd.": "mhvyf",
    "kawasaki heavy industries, ltd.": "kwhiy",
    "fuji electric co., ltd.": "felty",
    "hitachi zosen corporation": "htzny",
    "jfe holdings, inc.": "jfeef",
    "nippon steel corporation": "nisty",
    "jfe holdings, inc.": "jfeef",
    "kobe steel, ltd.": "kbsty",
    "sumitomo metal industries, ltd.": "smmly",
    "nisshin steel co., ltd.": "nssty",
    "nucor corporation": "nue",
    "united states steel corporation": "x",
    "steel dynamics, inc.": "stld",
    "posco": "pkx",
    "nippon steel corporation": "nisty",
    "jfe holdings, inc.": "jfeef",
    "nucor corporation": "nue",
    "united states steel corporation": "x",
    "steel dynamics, inc.": "stld",
    "posco": "pkx",
    "gerdau s.a.": "ggb",
    "ternium s.a.": "tx",
    "arcelormittal": "mt",
    "vale s.a.": "vale",
    "rio tinto group": "rio",
    "bhp": "bhp",
    "freeport-mcmoran inc.": "fcx",
    "alcoa corporation": "aa",
    "norsk hydro asa": "nhydy",
    "vedanta limited": "vedl",
    "bhp": "bhp",
    "rio tinto group": "rio",
    "anglo american plc": "ngloy",
    "mitsubishi corporation": "msbhy",
    "glencore plc": "glncy",
    "bhp": "bhp",
    "rio tinto group": "rio",
    "vale s.a.": "vale",
    "bhp": "bhp",
    "rio tinto group": "rio",
    "vale s.a.": "vale",
    "bhp": "bhp",
    "rio tinto group": "rio",
    "vale s.a.": "vale",
    "bhp": "bhp",
    "rio tinto group": "rio",
    "vale s.a.": "vale",
    "goldcorp inc.": "gg",
    "newmont corporation": "nem",
    "barrick gold corporation": "gold",
    "anglogold ashanti limited": "au",
    "gold fields limited": "gfi",
    "kinross gold corporation": "kgc",
    "agnico eagle mines limited": "aem",
    "yamana gold inc.": "auy",
    "eldorado gold corporation": "ego",
    "iamgold corporation": "iag",
    "alamos gold inc.": "agi",
    "newcrest mining limited": "ncmgy",
    "northern star resources limited": "nstgy",
    "evolution mining limited": "cahpf",
    "barrick gold corporation": "gold",
    "newmont corporation": "nem",
    "anglogold ashanti limited": "au",
    "gold fields limited": "gfi",
    "kinross gold corporation": "kgc",
    "agnico eagle mines limited": "aem",
    "yamana gold inc.": "auy",
    "barrick gold corporation": "gold",
    "newmont corporation": "nem",
    "anglogold ashanti limited": "au",
    "gold fields limited": "gfi",
    "kinross gold corporation": "kgc",
    "agnico eagle mines limited": "aem",
    "yamana gold inc.": "auy",
    "eldorado gold corporation": "ego",
    "iamgold corporation": "iag"
}